name: Deploy Frontend to EC2

on:
  push:
    branches:
      - feature/fe/78 # dev/fe 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 7. Lighthouse 검사 및 결과 저장
      - name: Run Lighthouse and Save Report
        run: |
          npm install -g @lhci/cli
          lhci autorun --url=https://inssaroute.shop --upload.target=filesystem --outputDir=$GITHUB_WORKSPACE/lighthouse-reports
      - name: Check if Lighthouse Reports Directory Exists
        run: |
          if [ ! -d "./lighthouse-reports/" ]; then
            echo "Lighthouse reports directory does not exist!";
            exit 1;
          fi      

     # AWS 자격 증명 구성
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3로 Lighthouse 결과 업로드
      - name: Deliver Lighthouse Reports to S3
        run: |
          aws s3 cp ./lighthouse-reports/ s3://${{ secrets.AWS_S3_BUCKET }}